### ISSUE TITLE
fakehub duplicates for different scenes

### ISSUE THREAD

**Issue by mukalaaa** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#5]
I added a fakehub library 300+ scenes 

The issue i am facing, multiple scenes the feature aubrey black for example are identified as one scene
have a look 
![3](https://user-images.githubusercontent.com/55691088/83998086-86b62b80-a968-11ea-93c7-f07d9c37a376.PNG)

the three videos you see, that are named fake family: University are:
faketaxi.17.11.30.aubrey.black.mp4
fakehuboriginals.18.06.02.aubrey.black.mp4
faketaxi.19.12.08.aubrey.black.mp4

They are different scenes, yet the plugin is identifying them as one. I also checked the PhoenixAdult Id for each one of them. it is one single ID 
![2](https://user-images.githubusercontent.com/55691088/83998353-0cd27200-a969-11ea-9074-90bc1647f058.PNG)

**Comment by DirtyRacer1337** [comment]
Looks like I fixed it, try on latest release. Notice I added building feature, so you don't need to build it for your own.

https://github.com/DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult/releases/latest

**Comment by mukalaaa** [comment]
yeah sorry but that did not fix it all 

have a look please 

![1](https://user-images.githubusercontent.com/55691088/84124649-2eecf280-aa44-11ea-9755-b65d1f5fdecf.PNG)

**Comment by DirtyRacer1337** [comment]
Add filenames

**Comment by mukalaaa** [comment]
I am sorry but I removed the library... I will add it again and report back to you

Thank You!
